const allChallenges = [
  {
    challengeId: "1",
    challengeStatus: "open",
    challengeImage: "/challengeImage.png",
    challengeName:
      "Design Dashboard for SokoFund which is the largest business",
    challengeDescription:
      "A Fintech company that is developing a Digital Financial Platform designed for businesses and their workforce in Africa is partnering with Umurava to run a Skills Challenge for Product Design.This Fintech Company offers Payroll Management System to Employers and Embedded Financial services and products to Employees and Gig Workers across Africa.",
    challegeRequirements: [
      "UX research to understand Project Requirements",
      "Understanding User Needs",
      "Understanding Business Goals",
      "Determine interaction between users",
      "Requirements Catalog",
    ],
    productDesign: [
      "User Interface Design for each step ",
      "Creating wireframes to outline the basic structure and layout of the web and mobile app.",
      "Designing visually appealing and user-friendly interfaces for the web and mobile apps focusing on usability and user experience.",
      "Ensuring the web application works seamlessly across web, mobile, and tablet devices.",
      "Provide a feedback session for in-development guidance",
    ],
    derivables: [
      "Requirements Catalog and User Interaction Diagram",
      "User Interface Mockups ",
      "Payroll and HR System Design Completed",
      "The Product Designer will provide all documents and deliverables to the client before the review meetings",
    ],
    note: [
      "Find Product Requirements Summary and Features Description for Saway Pay HERE",
    ],
    challengeCategory: "Web Design",
    challengePrize: "$150 - $400",
    challengeSkills: ["UI/UX Design", "User Research", "Research"],
    challengeSeniorityLevel: "(Junior,Intermediate,Senior)",
    challengeTimeline: "15 days",
  },
  {
    challengeId: "2",
    challengeStatus: "open",
    challengeImage: "/challengeImage.png",
    challengeName: "Create a Social Media App",
    challengeDescription:
      "A Fintech company that is developing a Digital Financial Platform designed for businesses and their workforce in Africa is partnering with Umurava to run a Skills Challenge for Product Design.This Fintech Company offers Payroll Management System to Employers and Embedded Financial services and products to Employees and Gig Workers across Africa.",
    challegeRequirements: [
      "UX research to understand Project Requirements",
      "Understanding User Needs",
      "Understanding Business Goals",
      "Determine interaction between users",
      "Requirements Catalog",
    ],
    productDesign: [
      "User Interface Design for each step ",
      "Creating wireframes to outline the basic structure and layout of the web and mobile app.",
      "Designing visually appealing and user-friendly interfaces for the web and mobile apps focusing on usability and user experience.",
      "Ensuring the web application works seamlessly across web, mobile, and tablet devices.",
      "Provide a feedback session for in-development guidance",
    ],
    derivables: [
      "Requirements Catalog and User Interaction Diagram",
      "User Interface Mockups ",
      "Payroll and HR System Design Completed",
      "The Product Designer will provide all documents and deliverables to the client before the review meetings",
    ],
    note: [
      "Find Product Requirements Summary and Features Description for Saway Pay HERE",
    ],
    challengeCategory: "Web Design",
    challengePrize: "$150 - $400",
    challengeSkills: ["React", "Firebase", "UI Design"],
    challengeSeniorityLevel: "(Intermediate, Senior)",
    challengeTimeline: "30 days",
  },
  {
    challengeId: "3",
    challengeStatus: "completed",
    challengeImage: "/challengeImage.png",
    challengeName: "Develop E-commerce Website",
    challengeDescription:
      "A Fintech company that is developing a Digital Financial Platform designed for businesses and their workforce in Africa is partnering with Umurava to run a Skills Challenge for Product Design.This Fintech Company offers Payroll Management System to Employers and Embedded Financial services and products to Employees and Gig Workers across Africa.",
    challegeRequirements: [
      "UX research to understand Project Requirements",
      "Understanding User Needs",
      "Understanding Business Goals",
      "Determine interaction between users",
      "Requirements Catalog",
    ],
    productDesign: [
      "User Interface Design for each step ",
      "Creating wireframes to outline the basic structure and layout of the web and mobile app.",
      "Designing visually appealing and user-friendly interfaces for the web and mobile apps focusing on usability and user experience.",
      "Ensuring the web application works seamlessly across web, mobile, and tablet devices.",
      "Provide a feedback session for in-development guidance",
    ],
    derivables: [
      "Requirements Catalog and User Interaction Diagram",
      "User Interface Mockups ",
      "Payroll and HR System Design Completed",
      "The Product Designer will provide all documents and deliverables to the client before the review meetings",
    ],
    note: [
      "Find Product Requirements Summary and Features Description for Saway Pay HERE",
    ],
    challengeCategory: "Web Design",
    challengePrize: "$150 - $400",
    challengeSkills: ["Node.js", "MongoDB", "Tailwind CSS"],
    challengeSeniorityLevel: "(Junior, Intermediate)",
    challengeTimeline: "20 days",
  },
  {
    challengeId: "4",
    challengeStatus: "completed",
    challengeImage: "/challengeImage.png",
    challengeName: "Build AI Chatbot",
    challengeDescription:
      "A Fintech company that is developing a Digital Financial Platform designed for businesses and their workforce in Africa is partnering with Umurava to run a Skills Challenge for Product Design.This Fintech Company offers Payroll Management System to Employers and Embedded Financial services and products to Employees and Gig Workers across Africa.",
    challegeRequirements: [
      "UX research to understand Project Requirements",
      "Understanding User Needs",
      "Understanding Business Goals",
      "Determine interaction between users",
      "Requirements Catalog",
    ],
    productDesign: [
      "User Interface Design for each step ",
      "Creating wireframes to outline the basic structure and layout of the web and mobile app.",
      "Designing visually appealing and user-friendly interfaces for the web and mobile apps focusing on usability and user experience.",
      "Ensuring the web application works seamlessly across web, mobile, and tablet devices.",
      "Provide a feedback session for in-development guidance",
    ],
    derivables: [
      "Requirements Catalog and User Interaction Diagram",
      "User Interface Mockups ",
      "Payroll and HR System Design Completed",
      "The Product Designer will provide all documents and deliverables to the client before the review meetings",
    ],
    note: [
      "Find Product Requirements Summary and Features Description for Saway Pay HERE",
    ],
    challengeCategory: "Web Design",
    challengePrize: "$150 - $400",
    challengeSkills: ["Python", "AI/ML", "NLP"],
    challengeSeniorityLevel: "(Senior)",
    challengeTimeline: "40 days",
  },
  {
    challengeId: "5",
    challengeStatus: "ongoing",
    challengeImage: "/challengeImage.png",
    challengeName: "Build AI Chatbot",
    challengeDescription:
      "A Fintech company that is developing a Digital Financial Platform designed for businesses and their workforce in Africa is partnering with Umurava to run a Skills Challenge for Product Design.This Fintech Company offers Payroll Management System to Employers and Embedded Financial services and products to Employees and Gig Workers across Africa.",
    challegeRequirements: [
      "UX research to understand Project Requirements",
      "Understanding User Needs",
      "Understanding Business Goals",
      "Determine interaction between users",
      "Requirements Catalog",
    ],
    productDesign: [
      "User Interface Design for each step ",
      "Creating wireframes to outline the basic structure and layout of the web and mobile app.",
      "Designing visually appealing and user-friendly interfaces for the web and mobile apps focusing on usability and user experience.",
      "Ensuring the web application works seamlessly across web, mobile, and tablet devices.",
      "Provide a feedback session for in-development guidance",
    ],
    derivables: [
      "Requirements Catalog and User Interaction Diagram",
      "User Interface Mockups ",
      "Payroll and HR System Design Completed",
      "The Product Designer will provide all documents and deliverables to the client before the review meetings",
    ],
    note: [
      "Find Product Requirements Summary and Features Description for Saway Pay HERE",
    ],
    challengeCategory: "Web Design",
    challengePrize: "$150 - $400",
    challengeSkills: ["Python", "AI/ML", "NLP"],
    challengeSeniorityLevel: "(Senior)",
    challengeTimeline: "40 days",
  },
  {
    challengeId: "5",
    challengeStatus: "ongoing",
    challengeImage: "/challengeImage.png",
    challengeName: "Build AI Chatbot",
    challengeDescription:
      "A Fintech company that is developing a Digital Financial Platform designed for businesses and their workforce in Africa is partnering with Umurava to run a Skills Challenge for Product Design.This Fintech Company offers Payroll Management System to Employers and Embedded Financial services and products to Employees and Gig Workers across Africa.",
    challegeRequirements: [
      "UX research to understand Project Requirements",
      "Understanding User Needs",
      "Understanding Business Goals",
      "Determine interaction between users",
      "Requirements Catalog",
    ],
    productDesign: [
      "User Interface Design for each step ",
      "Creating wireframes to outline the basic structure and layout of the web and mobile app.",
      "Designing visually appealing and user-friendly interfaces for the web and mobile apps focusing on usability and user experience.",
      "Ensuring the web application works seamlessly across web, mobile, and tablet devices.",
      "Provide a feedback session for in-development guidance",
    ],
    derivables: [
      "Requirements Catalog and User Interaction Diagram",
      "User Interface Mockups ",
      "Payroll and HR System Design Completed",
      "The Product Designer will provide all documents and deliverables to the client before the review meetings",
    ],
    note: [
      "Find Product Requirements Summary and Features Description for Saway Pay HERE",
    ],
    challengeCategory: "Web Design",
    challengePrize: "$150 - $400",
    challengeSkills: ["Python", "AI/ML", "NLP"],
    challengeSeniorityLevel: "(Senior)",
    challengeTimeline: "40 days",
  },
];

export default allChallenges;
